#############################################################################
# Makefile for building: mission
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  mission.pro
# Template: app
# Command: /opt/Qt5.4.2/5.4/gcc_64/bin/qmake -spec linux-g++ -o Makefile mission.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.4.2/5.4/gcc_64/include -I/opt/Qt5.4.2/5.4/gcc_64/include/QtQuick -I/opt/Qt5.4.2/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.2/5.4/gcc_64/include/QtQml -I/opt/Qt5.4.2/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.2/5.4/gcc_64/include/QtCore -I. -I/opt/Qt5.4.2/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.4.2/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mission1.0.0
DISTDIR = /home/null/mywork/mission/.tmp/mission1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5.4.2/5.4/gcc_64 -Wl,-rpath,/opt/Qt5.4.2/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.4.2/5.4/gcc_64/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp \
		qrc_image.cpp \
		qrc_particle_image.cpp \
		qrc_start_image.cpp \
		qrc_background_image.cpp
OBJECTS       = main.o \
		qrc_qml.o \
		qrc_image.o \
		qrc_particle_image.o \
		qrc_start_image.o \
		qrc_background_image.o
DIST          = /opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/lex.prf \
		mission.pro  main.cpp
QMAKE_TARGET  = mission
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = mission


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mission.pro /opt/Qt5.4.2/5.4/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/lex.prf \
		mission.pro \
		qml.qrc \
		image.qrc \
		particle_image.qrc \
		start_image.qrc \
		background_image.qrc \
		/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Quick.prl \
		/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.prl \
		/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Qml.prl \
		/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Network.prl
	$(QMAKE) -spec linux-g++ -o Makefile mission.pro
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.4.2/5.4/gcc_64/mkspecs/features/lex.prf:
mission.pro:
qml.qrc:
image.qrc:
particle_image.qrc:
start_image.qrc:
background_image.qrc:
/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Quick.prl:
/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.prl:
/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Qml.prl:
/opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile mission.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc image.qrc particle_image.qrc start_image.qrc background_image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp qrc_image.cpp qrc_particle_image.cpp qrc_start_image.cpp qrc_background_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_image.cpp qrc_particle_image.cpp qrc_start_image.cpp qrc_background_image.cpp
qrc_qml.cpp: qml.qrc \
		play.qml \
		menu.qml \
		replace.qml \
		start.qml \
		Qt5_NMap_CarouselDemo.qml \
		Change_Background.qml \
		test_menu.qml \
		main.qml \
		content/ContentModel.qml \
		content/FpsItem.qml \
		content/ListItem.qml \
		content/NMapEffect.qml \
		content/NMapLightSource.qml \
		content/Calendar.qml \
		content/test.qml
	/opt/Qt5.4.2/5.4/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_image.cpp: image.qrc \
		image/icon_4.png \
		image/exit.jpg \
		image/back.png \
		image/picture_2.jpg \
		image/menu.jpg \
		image/icon_5.png \
		image/background.jpg \
		image/quit.png \
		image/picture_1.jpg \
		content/images/13s.png \
		content/images/3n.png \
		content/images/car.png \
		content/images/9n.png \
		content/images/3s.png \
		content/images/9s.png \
		content/images/2n.png \
		content/images/8n.png \
		content/images/10n.png \
		content/images/spot.png \
		content/images/2s.png \
		content/images/background_lab.png \
		content/images/8s.png \
		content/images/1n.png \
		content/images/10s.png \
		content/images/set.png \
		content/images/1s.png \
		content/images/15n.png \
		content/images/15s.png \
		content/images/1.png \
		content/images/2.png \
		content/images/10.png \
		content/images/3.png \
		content/images/13.png \
		content/images/13n.png \
		content/images/15.png \
		content/images/8.png \
		content/images/arrow-right.png \
		content/images/spinner.png \
		content/images/9.png
	/opt/Qt5.4.2/5.4/gcc_64/bin/rcc -name image image.qrc -o qrc_image.cpp

qrc_particle_image.cpp: particle_image.qrc \
		particle_image/glowdot.png \
		particle_image/greenStar.png \
		particle_image/fuzzydot.png \
		particle_image/noise.png \
		particle_image/particle.jpg \
		particle_image/star.png \
		particle_image/text.jpg
	/opt/Qt5.4.2/5.4/gcc_64/bin/rcc -name particle_image particle_image.qrc -o qrc_particle_image.cpp

qrc_start_image.cpp: start_image.qrc \
		start_image/20.bmp \
		start_image/21.bmp \
		start_image/22.bmp \
		start_image/1.bmp \
		start_image/2.bmp \
		start_image/10.bmp \
		start_image/3.bmp \
		start_image/11.bmp \
		start_image/12.bmp \
		start_image/4.bmp \
		start_image/5.bmp \
		start_image/13.bmp \
		start_image/6.bmp \
		start_image/14.bmp \
		start_image/7.bmp \
		start_image/15.bmp \
		start_image/8.bmp \
		start_image/16.bmp \
		start_image/9.bmp \
		start_image/17.bmp \
		start_image/18.bmp \
		start_image/19.bmp
	/opt/Qt5.4.2/5.4/gcc_64/bin/rcc -name start_image start_image.qrc -o qrc_start_image.cpp

qrc_background_image.cpp: background_image.qrc \
		background_image/Heise12.jpg \
		background_image/Heise13.jpg \
		background_image/Heise14.jpg \
		background_image/Heise15.jpg \
		background_image/Heise16.jpg \
		background_image/Heise17.jpg \
		background_image/Heise18.jpg \
		background_image/Heise19.jpg \
		background_image/Heise1.jpg \
		background_image/Heise2.jpg \
		background_image/Heise20.jpg \
		background_image/Heise3.jpg \
		background_image/Heise4.jpg \
		background_image/Heise5.jpg \
		background_image/Heise6.jpg \
		background_image/Heise7.jpg \
		background_image/Heise10.jpg \
		background_image/Heise8.jpg \
		background_image/Heise11.jpg \
		background_image/Heise9.jpg
	/opt/Qt5.4.2/5.4/gcc_64/bin/rcc -name background_image background_image.qrc -o qrc_background_image.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp /opt/Qt5.4.2/5.4/gcc_64/include/QtGui/QGuiApplication \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/QQmlApplicationEngine \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qqmlapplicationengine.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qqmlengine.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qjsengine.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qjsvalue.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qtqmlglobal.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qqmlerror.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtQml/qqmldebug.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.2/5.4/gcc_64/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

qrc_particle_image.o: qrc_particle_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_particle_image.o qrc_particle_image.cpp

qrc_start_image.o: qrc_start_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_start_image.o qrc_start_image.cpp

qrc_background_image.o: qrc_background_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_background_image.o qrc_background_image.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/mission/bin || mkdir -p $(INSTALL_ROOT)/opt/mission/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/mission/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/mission/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/mission/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/mission/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

